name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*-beta'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Runner Docker Image
        run: docker build . --file Dockerfile --tag justnz/runner:${{ github.sha }} --tag justnz/runner:${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          docker push justnz/runner:${{ github.sha }}
          docker push justnz/runner:${{ github.ref_name }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: go build -v ./...

      - name: Build Release Binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o bin/runner-darwin-amd64 ./cmd/runner
          GOOS=darwin GOARCH=arm64 go build -o bin/runner-darwin-arm64 ./cmd/runner
          GOOS=linux GOARCH=amd64 go build -o bin/runner-linux-amd64 ./cmd/runner

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          artifacts: 'bin/*'
          skipIfReleaseExists: true
          generateReleaseNotes: true
          prerelease: true
          token: ${{ secrets.ACCESS_TOKEN }}
