name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-beta.*'
      - 'v*.*.*-alpha.*'
      - 'v*.*.*-rc.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Runner Docker Image (Stable)
        if: ${{ !contains(github.ref_name, '-beta') && !contains(github.ref_name, '-alpha') && !contains(github.ref_name, '-rc') }}
        run: docker build . --file Dockerfile --tag ghcr.io/justlabv1/runner:latest --tag ghcr.io/justlabv1/runner:${{ github.sha }} --tag ghcr.io/justlabv1/runner:${{ github.ref_name }}

      - name: Build Runner Docker Image (Pre-release)
        if: ${{ contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') || contains(github.ref_name, '-rc') }}
        run: docker build . --file Dockerfile --tag ghcr.io/justlabv1/runner:beta --tag ghcr.io/justlabv1/runner:${{ github.sha }} --tag ghcr.io/justlabv1/runner:${{ github.ref_name }}
      
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push Docker Images (Stable)
        if: ${{ !contains(github.ref_name, '-beta') && !contains(github.ref_name, '-alpha') && !contains(github.ref_name, '-rc') }}
        run: |
          docker push ghcr.io/justlabv1/runner:latest
          docker push ghcr.io/justlabv1/runner:${{ github.sha }}
          docker push ghcr.io/justlabv1/runner:${{ github.ref_name }}
      
      - name: Push Docker Images (Pre-release)
        if: ${{ contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') || contains(github.ref_name, '-rc') }}
        run: |
          docker push ghcr.io/justlabv1/runner:beta
          docker push ghcr.io/justlabv1/runner:${{ github.sha }}
          docker push ghcr.io/justlabv1/runner:${{ github.ref_name }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: go build -v ./...

      - name: Build Release Binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o bin/runner-darwin-amd64 ./cmd/runner
          GOOS=darwin GOARCH=arm64 go build -o bin/runner-darwin-arm64 ./cmd/runner
          GOOS=linux GOARCH=amd64 go build -o bin/runner-linux-amd64 ./cmd/runner

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ contains(github.ref_name, '-beta') && format('🚧 Beta Release {0}', github.ref_name) || contains(github.ref_name, '-alpha') && format('🔬 Alpha Release {0}', github.ref_name) || contains(github.ref_name, '-rc') && format('🎯 Release Candidate {0}', github.ref_name) || format('🚀 Release {0}', github.ref_name) }}
          tag: ${{ github.ref_name }}
          artifacts: 'bin/*'
          skipIfReleaseExists: true
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') || contains(github.ref_name, '-rc') }}
